### ISSUE TITLE
Typing "ura" into JEI crashes game

### ISSUE THREAD

**Issue by Filmos** [Filmos/FilmPack#163]
```
java.lang.NullPointerException: Rendering item
	at vazkii.botania.client.render.tile.RenderTilePylon.access$200(RenderTilePylon.java:41) ~[?:1.16-402] {re:classloading}
	at vazkii.botania.client.render.tile.RenderTilePylon$TEISR.func_239207_a_(RenderTilePylon.java:144) ~[?:1.16-402] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:252) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:407) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:447) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:436) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:extract-item-color,xf:fml:quark:get-armor-color,xf:fml:quark:get-glint-color,xf:fml:quark:get-glint-direct-color,xf:OptiFine:default}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:40) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:26) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.render.IngredientListElementRenderer.renderSlow(IngredientListElementRenderer.java:81) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:204) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:107) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:114) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:179) ~[?:7.0.1.10] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:85) ~[?:7.0.1.10] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_865_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.func_238651_a_(Screen.java:344) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_230446_a_(Screen.java:338) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?] {}
```

**Comment by Filmos** [comment]
This was caused by OptiFine
