### ISSUE TITLE
Crash spowodowany computercraftem

### ISSUE THREAD

**Issue by Filmos** [Filmos/FilmPack#25]
Pojawia się podczas korzystania z JEI więc jest dosyć groźny.

```
[10/7/2020 20:29:56 PM] Caused by: java.lang.IllegalStateException: not enough data
[10/7/2020 20:29:56 PM] 	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[?:?]
[10/7/2020 20:29:56 PM] 	at dan200.computercraft.client.render.TurtleMultiModel.transformQuadsTo(TurtleMultiModel.java:146) ~[?:1.89.1]
[10/7/2020 20:29:56 PM] 	at dan200.computercraft.client.render.TurtleMultiModel.buildQuads(TurtleMultiModel.java:73) ~[?:1.89.1]
[10/7/2020 20:29:56 PM] 	at dan200.computercraft.client.render.TurtleMultiModel.getQuads(TurtleMultiModel.java:63) ~[?:1.89.1]
[10/7/2020 20:29:56 PM] 	at dan200.computercraft.client.render.TurtleMultiModel.func_200117_a(TurtleMultiModel.java:49) ~[?:1.89.1]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.renderer.ItemRenderer.func_229114_a_(ItemRenderer.java:121) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:180) ~[?:?]
[10/7/2020 20:29:56 PM] 	at codechicken.lib.render.item.CCRenderItem.func_229111_a_(CCRenderItem.java:37) ~[?:1.15.2-3.3.0.373]
[10/7/2020 20:29:56 PM] 	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:62) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:29) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:168) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:82) ~[?:6.0.2.12]
[10/7/2020 20:29:56 PM] 	at net.minecraftforge.eventbus.ASMEventHandler_1094_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
[10/7/2020 20:29:56 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:369) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:363) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:82) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?]
[10/7/2020 20:29:56 PM] 	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
[10/7/2020 20:29:56 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[10/7/2020 20:29:56 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
[10/7/2020 20:29:56 PM] 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:745) ~[?:?]
[10/7/2020 20:29:56 PM] 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:798) ~[?:?]
[10/7/2020 20:29:56 PM] 	... 13 more
```

**Comment by Filmos** [comment]
Nie da się zreprodukować, prawdopodobnie spatchowane w updatcie moda.
