### ISSUE TITLE
Nie można zniszczyć insanium furnace

### ISSUE THREAD

**Issue by Filmos** [Filmos/FilmPack#35]
```
[12/7/2020 14:07:26 PM] java.lang.RuntimeException: class com.focamacho.mysticaladaptations.tileentity.InsaniumFurnaceTileEntity is missing a mapping! This is a bug!
[12/7/2020 14:07:26 PM] 	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:64) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.tileentity.TileEntity.func_189515_b(TileEntity.java:58) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.tileentity.LockableTileEntity.func_189515_b(LockableTileEntity.java:35) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.tileentity.AbstractFurnaceTileEntity.func_189515_b(AbstractFurnaceTileEntity.java:178) ~[?:?]
[12/7/2020 14:07:26 PM] 	at io.github.strikerrocker.vt.tweaks.FurnaceBrokenXP.onBlockBroken(FurnaceBrokenXP.java:67) ~[?:1.15.2.1.5.27]
[12/7/2020 14:07:26 PM] 	at net.minecraftforge.eventbus.ASMEventHandler_836_FurnaceBrokenXP_onBlockBroken_BreakEvent.invoke(.dynamic) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
[12/7/2020 14:07:26 PM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
[12/7/2020 14:07:26 PM] 	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:568) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:226) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:216) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:140) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:833) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?]
[12/7/2020 14:07:26 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
[12/7/2020 14:07:26 PM] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by Filmos** [comment]
Usunięte przy aktualizacji do 1.16
