### ISSUE TITLE
Crashe

### ISSUE THREAD

**Issue by Filmos** [Filmos/FilmPack#38]
Losowy crash na starcie
```
[12/7/2020 18:36:26 PM] [18:36:26] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[12/7/2020 18:36:26 PM] [18:36:26] [Render thread/FATAL]: EventBus 0 shutting down - future events will not be posted.
[12/7/2020 18:36:26 PM] java.lang.Exception: stacktrace
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) ~[eventbus-2.2.0-service.jar:?]
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) ~[?:?]
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?]
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?]
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.main.Main.main(SourceFile:166) ~[client-1.15.2.jar:?]
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[12/7/2020 18:36:26 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
[12/7/2020 18:36:26 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.30.jar:31.2]
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[12/7/2020 18:36:26 PM] [18:36:26] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
[12/7/2020 18:36:26 PM] // Shall we play a game?
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] Time: 7/12/20 6:36 PM
[12/7/2020 18:36:26 PM] Description: Initializing game
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] java.lang.ExceptionInInitializerError: null
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.FontResourceManager.func_212318_b(SourceFile:152) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_251] {}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.FontResourceManager.func_211504_a(SourceFile:151) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:408) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.main.Main.main(SourceFile:166) ~[client-1.15.2.jar:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
[12/7/2020 18:36:26 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
[12/7/2020 18:36:26 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.30.jar:31.2] {}
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
[12/7/2020 18:36:26 PM] Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
[12/7/2020 18:36:26 PM] 	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.rehash(ObjectOpenCustomHashSet.java:683) ~[fastutil-8.2.1.jar:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet.addOrGet(ObjectOpenCustomHashSet.java:360) ~[fastutil-8.2.1.jar:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.renderer.RenderType$Type.func_228676_c_(SourceFile:655) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.renderer.RenderType$Type.func_228675_b_(SourceFile:638) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.renderer.RenderType.func_228633_a_(SourceFile:402) ~[?:?] {re:classloading,pl:accesstransformer:B}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.renderer.RenderType.func_228658_l_(SourceFile:320) ~[?:?] {re:classloading,pl:accesstransformer:B}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.EmptyGlyph.<init>(SourceFile:10) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.Font.<clinit>(SourceFile:30) ~[?:?] {re:classloading}
[12/7/2020 18:36:26 PM] 	... 15 more
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[12/7/2020 18:36:26 PM] ---------------------------------------------------------------------------------------
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] -- Head --
[12/7/2020 18:36:26 PM] Thread: Render thread
[12/7/2020 18:36:26 PM] Stacktrace:
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.FontResourceManager.func_212318_b(SourceFile:152)
[12/7/2020 18:36:26 PM] 	at java.util.HashMap.computeIfAbsent(Unknown Source)
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.gui.fonts.FontResourceManager.func_211504_a(SourceFile:151)
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:408)
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] -- Initialization --
[12/7/2020 18:36:26 PM] Details:
[12/7/2020 18:36:26 PM] Stacktrace:
[12/7/2020 18:36:26 PM] 	at net.minecraft.client.main.Main.main(SourceFile:166)
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12/7/2020 18:36:26 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12/7/2020 18:36:26 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12/7/2020 18:36:26 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[12/7/2020 18:36:26 PM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[12/7/2020 18:36:26 PM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[12/7/2020 18:36:26 PM] 
[12/7/2020 18:36:26 PM] -- System Details --
[12/7/2020 18:36:26 PM] Details:
[12/7/2020 18:36:26 PM] 	Minecraft Version: 1.15.2
[12/7/2020 18:36:26 PM] 	Minecraft Version ID: 1.15.2
[12/7/2020 18:36:26 PM] 	Operating System: Windows 10 (amd64) version 10.0
[12/7/2020 18:36:26 PM] 	Java Version: 1.8.0_251, Oracle Corporation
[12/7/2020 18:36:26 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[12/7/2020 18:36:26 PM] 	Memory: 5815332184 bytes (5545 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
[12/7/2020 18:36:26 PM] 	CPUs: 16
[12/7/2020 18:36:26 PM] 	JVM Flags: 12 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx8192M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
[12/7/2020 18:36:26 PM] 	ModLauncher: 5.1.0+69+master.79f13f7
[12/7/2020 18:36:26 PM] 	ModLauncher launch target: fmlclient
[12/7/2020 18:36:26 PM] 	ModLauncher naming: srg
[12/7/2020 18:36:26 PM] 	ModLauncher services: 
[12/7/2020 18:36:26 PM] 		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
[12/7/2020 18:36:26 PM] 		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
[12/7/2020 18:36:26 PM] 		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
[12/7/2020 18:36:26 PM] 	FML: 31.2
[12/7/2020 18:36:26 PM] 	Forge: net.minecraftforge:31.2.30
[12/7/2020 18:36:26 PM] 	FML Language Providers: 
[12/7/2020 18:36:26 PM] 		javafml@31.2
[12/7/2020 18:36:26 PM] 		minecraft@1
[12/7/2020 18:36:26 PM] 	Mod List: 
[12/7/2020 18:36:26 PM] 		vanillaextension-1.15.2-1.0.3.jar Vanilla Extension {vanillaextension@1.15.2-1.0.3 CREATE_REGISTRIES}
[12/7/2020 18:36:26 PM] 		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 CREATE_REGISTRIES}
```

**Comment by mstaczek** [comment]
Others are unable to reproduce this crash.

**Comment by Filmos** [comment]
Inny crash podczas biegania po serwerze:
```
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] # A fatal error has been detected by the Java Runtime Environment:
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000032d5bce, pid=15924, tid=0x0000000000003c48
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] # JRE version: Java(TM) SE Runtime Environment (8.0_251-b08) (build 1.8.0_251-b08)
[16/7/2020 16:55:48 PM] # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.251-b08 mixed mode windows-amd64 compressed oops)
[16/7/2020 16:55:48 PM] # Problematic frame:
[16/7/2020 16:55:48 PM] # j  net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(FFFLnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$CompiledChunk;Lnet/minecraft/client/renderer/RegionRenderCacheBuilder;)Ljava/util/Set;+249
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] # An error report file with more information is saved as:
[16/7/2020 16:55:48 PM] # **USERSDIR**\instances\FilmPackNEW\hs_err_pid15924.log
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] # If you would like to submit a bug report, please visit:
[16/7/2020 16:55:48 PM] #   http://bugreport.java.com/bugreport/crash.jsp
[16/7/2020 16:55:48 PM] #
[16/7/2020 16:55:48 PM] AL lib: (EE) alc_cleanup: 1 device not closed
[16/7/2020 16:55:48 PM] Checking for updated files!
[16/7/2020 16:55:48 PM] Checking for updated files!
[16/7/2020 16:55:49 PM] Finished downloading updated files!
```

**Comment by Filmos** [comment]
Prawdopodobnie wina po stronie kompa a nie modpacka, zamykam.
